site_name: BirdNET
site_url: https://mydomain.org/mysite
repo_name: BirdNET Analyzer
repo_url: https://github.com/birdnet-team/BirdNET-Analyzer
extra_css:
  - stylesheets/extra.css
#plugins:
#  - privacy:
#      enabled: !ENV [CI, false]
theme:
  name: material
  logo: assets/clo_birdnet_horizontal.png
  palette:    
      scheme: default
  font:
    text: Roboto
    code: Roboto Mono