site_name: BirdNET
site_url: https://mydomain.org/mysite
repo_name: BirdNET Analyzer
repo_url: https://github.com/birdnet-team/BirdNET-Analyzer
extra_css:
  - stylesheets/extra.css
#plugins:
#  - privacy:
#      enabled: !ENV [CI, false]
theme:
  name: material
  logo: assets/clo_birdnet_horizontal.png
  favicon: assets/clo_sapsucker.png
  palette:
      scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  icon:
    annotation: material/arrow-right-circle-outline
  custom_dir: overrides
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      